services:
  frigate:
    container_name: frigate

    build:
      context: .
      dockerfile: docker/main/Dockerfile
      target: frigate

    image: frigate:stable

    restart: unless-stopped
    stop_grace_period: 30s
    shm_size: "256mb"

    ports:
      - "8971:8971"
      - "5000:5000"
      - "8554:8554"
      - "8555:8555/tcp"
      - "8555:8555/udp"

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config
      - ./debug:/media/frigate

#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: 1
#              capabilities: [gpu]

    environment:
      YOLO_MODELS: ""

    extra_hosts:
      - "host.docker.internal:host-gateway"
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:2.0
    command: mosquitto -c /mosquitto-no-auth.conf
    ports:
      - "1883:1883"